build:
  image: python
  commands:
    - python setup.py install
    - python setup.py test

  deploy:
    ssh:
      host: 188.166.218.1
      user: deploy
      port: 22
      commands:
        - touch hello
        - touch world
