build:
  image: python
  environment:
    - TEST_KEY="$(cat ~/.ssh/id_rsa)"
  commands:
    - python setup.py install
    - python setup.py test
    - pwd
    - ls -la
    - ls -la ~/.ssh
    - echo $TEST_KEY

deploy:
  ssh:
    host: 188.166.218.1
    user: deploy
    port: 22
    commands:
      - ./deploy.sh
      - touch world
