debug: true

build:
  image: python

deploy:
  ssh:
    image: framgia/drone-ssh-py
    host: 188.166.218.1
    user: deploy
    port: 22
    pre_commands:
      - ls -la
      - pwd
      - cat /root/.ssh/id_rsa
    commands:
      - touch temp
