debug: true

build:
  image: python
  environment:
    - TEST_KEY="$(cat ~/.ssh/id_rsa)"
  commands:
    - ls -la /
    - ls -la /drone
    - pwd
    - ls -la
    - echo $TEST_KEY

deploy:
  ssh:
    image: vigov5/drone-ssh-plus
    host: 188.166.218.1
    user: deploy
    port: 22
    pre_commands:
      - whoami
      - ls -la
    commands:
      - ./deploy.sh
      - touch world
